const posts = [
	{
		slug: 'socialbakers-project',
		name: 'Socialbakers',
    img: {
      listingPoster: 'sb/sb-1.jpg',
      listingPosterSliced: 'sb/sb-2.jpg',
    },
    video: 'sb/sb.mp4',
		role: 'Javascript Frontend Web Developer / React Coder',
		year: 'Jan 2017 - Present',
    link: 'https://www.socialbakers.com/',
    jobDescription: [
      'Transform existing Socialbakers website to SSR PWA connected to headless CMS', 
      'Complete redesign of main Socialbakers site.',
      'Creating Socialbakers web UI pattern library.',
      'Creating microsites.',
      'Setting standards and code styles.',
    ],
		tags: [
			'SSR PWA',
			'Headless CMS',
			'React.js',
			'React hooks',
			'React contextAPI',
			'Redux',
			'Styled Components',
			'Flow.js',
			'Storybook',
			'Lighthouse/PageSpeed',
			'Performance',
      'Git',
      'HTML5',
      'CSS3',
      'ES6',
      'UI Library',
      'Css grid',
      'Flexbox',
      'Accessibility',
      'Responsive',
      'Figma',
    ],
  },
  {
    slug: 'jobs-project',
    name: 'Jobs.cz',
    img: {
      listingPoster: 'jobs/jobs-1.jpg',
      listingPosterSliced: 'jobs/jobs-2.jpg',
    },
    video: 'jobs/jobs.mp4',
    role: 'Frontend Web Developer / Coder',
    year: 'Jul 2015 – Dec 2016',
    link: 'https://www.jobs.cz/',
    jobDescription: [
      'Create, maintain and update components in LMC\'s \'jobs-ui\' library using Grunt, Less, BEM, HTML5, JS ES6, jQuery',
      'Changes/updates to React components using JS and JSX',
      'Create, maintain and update LMC\'s web site www.jobs.cz and firmy.jobs.cz',
      'Close cooperation with Product Managers, UX designers and Back end developers',
    ],
    tags: [
      'React.js',
      'JSX',
      'LESS',
      'Grunt',
      'BEM',
      'UI Library',
      'HTML5',
      'CSS3',
      'ES6,',
      'jQuery',
      'Git',
      'Flexbox',
      'Accessibility',
      'Responsive',
    ],
  },
  {
    slug: 'avg-project',
    name: 'AVG',
    img: {
      listingPoster: 'avg/avg-1.jpg',
      listingPosterSliced: 'avg/avg-2.jpg',
    },
    video: 'avg/avg.mp4',
    role: 'Web Coder',
    year: 'Aug 2011 – Jul 2015',
    link: 'https://www.avg.com/',
    jobDescription: [
      'Redesign of main AVG site.',
      'Creating mobile application webview screens with devstack runs on node.js, gulp, Sass, Bootstrap, bower, jade',
      'PSD to HTML on daily basis, hand coded output(landing pages, microsites, emails, campaigns, inapp)',
      'Deliver solution for various application campaign flows, and requests from marketing and monetization team',
      'Corporate and inapp pages optimalization for localization',
      'Close cooperation with various teams (campaign, marketing, monetization, back-end, licence server, localization etc...)',
      'Cross-browser optimalization (IE6, IE7, and all major browsers)',
      'Bug fixing',
      'Content management (editing and updating content in AVG Content Management System)',
      'Tracking implementation',
      'Testing',
    ],
    tags: [
      'HTML',
      'CSS',
      'SCSS',
      'JS',
      'jQuery',
      'Photoshop',
      'Jade/Pug',
      'Gulp',
      'Bower',
      'SVN',
    ],
  },
  {
    slug: 'slavne-stavby-project',
    name: 'Slavne Stavby',
    img: {
      listingPoster: 'sls/sls-1.jpg',
      listingPosterSliced: 'sls/sls-2.jpg',
    },
    video: 'sls/sls.mp4',
    role: 'Frontend Web Developer / freelance',
    year: '2019',
    link: 'http://slavnestavby.cz/',
    jobDescription: [
      'Freelancing',
      'Coding',
      'Styling',
      'Javascript',
    ],
    tags: [
      'React.js',
      'Redux',
      'Styled Components',
      'Git',
      'HTML5',
      'CSS3',
      'ES6',
      'Flexbox',
      'Responsive',
    ],
  },
  {
    slug: 'high-level-magazine-project',
    name: 'High Level Magazine',
    img: {
      listingPoster: 'hlm/hlm-1.jpg',
      listingPosterSliced: 'hlm/hlm-2.jpg',
    },
    video: 'hlm/hlm.mp4',
    role: 'Coder / freelance',
    year: '2019',
    link: 'https://www.highlevelmagazine.com/',
    jobDescription: [
      'Freelancing',
      'Coding',
      'Styling',
      'Javascript',
    ],
    tags: [
      'SCSS',
      'Gulp',
      'BEM',
      'HTML5',
      'CSS3',
      'jQuery',
      'Bootstrap',
      'Git',
      'Flexbox',
      'Accessibility',
      'Responsive',
    ],
  },
  {
    slug: 'business-soiree-project',
    name: 'The Business Soiree',
    img: {
      listingPoster: 'bs/bs-1.jpg',
      listingPosterSliced: 'bs/bs-2.jpg',
    },
    video: 'bs/bs.mp4',
    role: 'Coder / freelance',
    year: '2019',
    link: 'https://www.thebusinesssoiree.com/',
    jobDescription: [
      'Freelancing',
      'Coding',
      'Styling',
      'Javascript',
    ],
    tags: [
      'SCSS',
      'Gulp',
      'BEM',
      'HTML5',
      'CSS3',
      'jQuery',
      'Bootstrap',
      'Git',
      'Flexbox',
      'Accessibility',
      'Responsive',
    ],
  },
  {
    slug: 'kill-bills-project',
    name: 'Kill Bill$ app.',
    img: {
      listingPoster: 'kb/kb-1.jpg',
      listingPosterSliced: 'kb/kb-2.jpg',
    },
    video: 'kb/kb.mp4',
    role: 'Javascript Frontend Web Developer / React Coder',
    year: '2019',
    link: 'https://peter-popluhar.github.io/kill-bills/',
    jobDescription: [
      'Side project application',
      'Architecture',
      'Programming',
      'Coding',
      'Styling',
      'Javascript',
    ],
    tags: [
      'React.js',
      'Redux',
      'Firebase',
      'AUTH',
      'Styled Components',
      'Material UI',
      'Git',
      'HTML5',
      'CSS3',
      'ES6',
      'Flexbox',
      'Accessibility',
      'Responsive',
    ],
  },
  {
    slug: 'bht-project',
    name: 'B.H.T.',
    img: {
      listingPoster: 'bht/bht-1.jpg',
      listingPosterSliced: 'bht/bht-2.jpg',
    },
    video: 'bht/bht.mp4',
    role: 'Coder / freelance',
    year: '2019',
    link: 'https://www.bhthydro.eu/',
    jobDescription: [
      'Freelancing',
      'Coding',
      'Styling',
      'Javascript',
    ],
    tags: [
      'SCSS',
      'Gulp',
      'BEM',
      'HTML5',
      'CSS3',
      'jQuery',
      'Bootstrap',
      'Git',
      'Flexbox',
      'Accessibility',
      'Responsive',
    ],
  },
];

 export default posts
