const data = [
	{
		link: 'item-1',
		name: 'Socialbakers',
		image: './../sb.jpg',
		bgImageSliced: './../sb-2.png',
		role: 'Javascript Frontend Web Developer / React Coder',
		year: 'Jan 2017 - Present',
		info: [
			'SSR PWA',
			'headless CMS',
			'react.js',
			'react hooks',
			'contextAPI',
			'redux',
			'styled components',
			'next.js',
			'flow',
			'storybook'
			],
  	},
  	{
		link: 'item-2',
		name: 'Jobs.cz',
		image: './../jobs.jpg',
		bgImageSliced: './../jobs-2.png',
		role: 'Frontend Web Developer / Coder',
		year: 'Jul 2015 – Dec 2016',
		info: [
			'react.js',
			'less',
			'BEM',
			'HTML5',
			'ES6,',
			'jQuery',
		],
  	},
  	{
		link: 'item-3',
		name: 'AVG',
		image: './../avg.jpg',
		bgImageSliced: './../avg.jpg',
		role: 'Frontend Web Developer / Coder',
		year: 'Aug 2011 – Jul 2015',
		info: [
			'SSR PWA',
			'headless CMS',
			'react.js',
			'react hooks',
			'contextAPI',
			'redux',
			'styled components',
			'next.js',
			'flow',
			'storybook'
		],
  	},
  	{
		link: 'item-4',
		name: 'Another',
		image: './../jobs.jpg',
		bgImageSliced: './../jobs-2.png',
		role: 'Frontend Web Developer / Coder',
		year: 'from Jan 2017',
		info: [
			'react.js',
			'less',
			'BEM',
			'HTML5',
			'ES6,',
			'jQuery',
		],
  	},
];

 export default data
